### ISSUE TITLE
Use with pure Dart packages

### ISSUE THREAD

**Issue by fusion44** [csnewman/flutter-go-bridge#1]
Hello!

Is there a plan to make this generator work with pure Dart packages? I can pin this package to a commit before the switch to the native toolchain, but I'll miss any improvements.

If not, no problem. Its probably called flutter go bridge for a reason.

**Comment by csnewman** [comment]
Native assets should also be available in the unstable Dart releases. The library and generated code shouldn't be using anything flutter specific as far as I'm aware

**Comment by csnewman** [comment]
Closing this issue now. Please do file an issue if you find any issues when using this toochain with Dart.
