### ISSUE TITLE
native_toolchain_go / go_native_toolchain

### ISSUE THREAD

**Issue by dcharkes** [csnewman/flutter-go-bridge#2]
Hi @csnewman!

Cool to see that we have an effort for making Dart and Go work together!

I have preregistered `package:native_toolchain_go`. If you will actively maintain this package, I'm happy to transfer ownership of that package name to you for consistency between:

* https://pub.dev/packages/native_toolchain_c
* https://github.com/dart-lang/native/issues/883

It might also be useful for you to chat with @knopp on some best practices and aligning the feature set and APIs. 😃

**Comment by csnewman** [comment]
Hi,

Thanks for reaching out. I had originally hoped to use `native_toolchain_go` for consistency but couldn't. I'd be happy to switch over to that package name for consistency.

Agreed that the API could do with some cleanup, however I've been deferring this until the Native Assets api becomes more stable.

**Comment by dcharkes** [comment]
> Thanks for reaching out. I had originally hoped to use `native_toolchain_go` for consistency but couldn't. I'd be happy to switch over to that package name for consistency.

I can't simply transfer the package immediately to you in the admin page.

>> You need to be an admin in both publishers to do a transfer.
>> They can invite you as admin, you do the transfer and then they can remove you from being admin.
>> Alternatively you may create a third publishers where only you two are admin and it acts only as intermediary.

If you have a publisher, can you invite me as an admin? Then I can transfer the package.

> Agreed that the API could do with some cleanup, however I've been deferring this until the Native Assets api becomes more stable.

Probably this one is also relevant for you:

* https://github.com/dart-lang/native/issues/995

**Comment by csnewman** [comment]
Ah, that's annoying. I've created an intermediary publisher and sent you an invite.

**Comment by dcharkes** [comment]
> Ah, that's annoying. I've created an intermediary publisher and sent you an invite.

Please invite my google email address: dacoharkes@google.com

**Comment by csnewman** [comment]
Thanks for transferring the package name. I have now switched over the package to the new name.
